name: stoppr
description: "Stop your sugar cravings"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parDts
# of the product and file versions while build-number is used as the build suffix.
version: 7.4.2+1

environment:
  sdk: ^3.7.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`.
# Alternatively, dependencies can be manually updated by changing the version numbers below.
# and then running `flutter pub get`. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase related
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_messaging: ^15.2.1
  cloud_firestore: ^5.6.5
  firebase_analytics: ^11.4.0
  firebase_storage: ^12.3.8

  google_sign_in: ^6.1.4
  sign_in_with_apple: 6.1.4
  crypto: ^3.0.3
  cloud_functions: ^5.3.4

  # State management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  bloc_concurrency: ^0.2.2

  # Permissions
  permission_handler: ^11.0.1

  # AI Integration
  dart_openai: ^5.1.0

  # Storage
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.0.0

  # Payments and Subscriptions
  # ios
  superwallkit_flutter: ^2.4.2
  # android
  # superwallkit_flutter: 2.0.8
  purchases_flutter: ^8.4.4
  purchases_ui_flutter: ^8.6.0
  app_links: ^6.4.0

  # UI/Widgets
  lottie: ^2.7.0
  video_player: ^2.10.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  shimmer: ^3.0.0
  skeletons: ^0.0.3
  flutter_svg: ^2.0.9
  flutter_animate: ^4.3.0
  flutter_staggered_animations: ^1.1.1
  camera: ^0.11.1
  image_picker: ^1.0.7
  flutter_markdown: ^0.7.1

  # Utilities
  path_provider: ^2.1.3
  intl: ^0.19.0
  url_launcher: ^6.2.2
  equatable: ^2.0.5
  uuid: ^4.2.1
  flutter_dotenv: ^5.1.0
  flutter_timezone: ^4.1.1
  timeago: ^3.7.0

  # Analytics
  mixpanel_flutter: ^2.3.4
  flutter_screenshot_detect: ^0.1.7

  # Image processing - NEW
  image: ^4.1.3

  # App version checking
  package_info_plus: ^8.0.0
  
  # Device information
  device_info_plus: ^11.5.0

  # HTTP requests
  http: ^1.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

  # New dependency
  app_tracking_transparency: ^2.0.4
  in_app_review: ^2.0.10
  audioplayers: ^5.2.1
  record: ^6.0.0
  audio_session: ^0.1.25
  wakelock_plus: ^1.2.6

  # In-app purchase
  in_app_purchase: ^3.1.11
  in_app_purchase_storekit: ^0.3.8+1
  flutter_local_notifications: ^19.0.0
  fl_chart: ^0.70.2
  crisp_chat: ^2.2.4
  firebase_crashlytics: ^4.3.4
  share_plus: ^10.1.4
  quick_actions: ^1.1.0

  # Widget support
  home_widget: ^0.7.0

  # Added dependency
  appsflyer_sdk: ^6.16.2

  # Emoji rendering for consistent iOS-style emojis
  flutter_emoji: ^2.5.1
  facebook_app_events: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Dev tools
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/food_scan_samples/
    - assets/images/global/
    - assets/images/learn_videos/
    - assets/images/logo/
    - assets/images/lotties/
    - assets/images/lotties/panicButton/
    - assets/images/lotties/wheel/
    - assets/images/onboarding/
    - assets/images/panic_button/
    - assets/images/ratings/
    - assets/images/stones/
    - assets/images/svg/
    - assets/images/testimonials/
    - assets/images/home/
    - assets/images/profile/
    - assets/images/learn/
    - assets/images/learn/thumbnails/
    - assets/images/rosaces/
    - assets/l10n/
    - assets/sounds/
    - assets/subtitles/
    - assets/subtitles/extracted/
    - assets/videos/
    - assets/changelog/
    - assets/articles/
    - assets/articles/en/
    - assets/articles/fr/
    - assets/articles/ru/
    - assets/articles/es/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ElzaRound
      fonts:
        - asset: assets/fonts/Elza Round/ElzaRoundVariable-Regular.ttf
          weight: 400
        - asset: assets/fonts/Elza Round/ElzaRoundVariable-Medium.ttf
          weight: 500
        - asset: assets/fonts/Elza Round/ElzaRoundVariable-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Elza Round/ElzaRoundVariable-Bold.ttf
          weight: 700
        - asset: assets/fonts/Elza Round/ElzaRoundVariable-Black.ttf
          weight: 900
        - asset: assets/fonts/Elza Round/ElzaRoundVariable-Italic.ttf
          style: italic
        - asset: assets/fonts/Elza Round/ElzaRoundVariable-MedIta.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Elza Round/ElzaRoundVariable-SemBdIta.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Elza Round/ElzaRoundVariable-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Elza Round/ElzaRoundVariable-BlackItalic.ttf
          style: italic
          weight: 900
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
